import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class ActivityMetricsService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * sessionId → string
   * playerId  → UUID (string)
   */
  async createMetric(
    sessionId: string,
    playerId: string, // ✅ FIXED: string (UUID)
    m: any,
  ) {
    return this.prisma.activityMetric.upsert({
      where: {
        // ✅ compound unique key generated by Prisma
        sessionId_playerId: {
          sessionId,
          playerId, // string UUID
        },
      },

      update: {
        totalDistance: m.totalDistance,
        hsrDistance: m.hsrDistance,
        sprintDistance: m.sprintDistance,
        topSpeed: m.topSpeed,
        sprintCount: m.sprintCount,

        acceleration: m.acceleration,
        deceleration: m.deceleration,
        maxAcceleration: m.maxAcceleration,
        maxDeceleration: m.maxDeceleration,

        playerLoad: m.playerLoad,
        powerScore: m.powerScore,

        hrMax: m.hrMax,
        timeInRedZone: m.timeInRedZone,
        percentInRedZone: m.percentInRedZone,
        hrRecoveryTime: m.hrRecoveryTime,

        recordedAt: new Date(
          m.createdAt ? Number(m.createdAt) * 1000 : Date.now(),
        ),
      },

      create: {
        sessionId,
        playerId, // ✅ UUID string

        totalDistance: m.totalDistance,
        hsrDistance: m.hsrDistance,
        sprintDistance: m.sprintDistance,
        topSpeed: m.topSpeed,
        sprintCount: m.sprintCount,

        acceleration: m.acceleration,
        deceleration: m.deceleration,
        maxAcceleration: m.maxAcceleration,
        maxDeceleration: m.maxDeceleration,

        playerLoad: m.playerLoad,
        powerScore: m.powerScore,

        hrMax: m.hrMax,
        timeInRedZone: m.timeInRedZone,
        percentInRedZone: m.percentInRedZone,
        hrRecoveryTime: m.hrRecoveryTime,

        recordedAt: new Date(
          m.createdAt ? Number(m.createdAt) * 1000 : Date.now(),
        ),
      },
    });
  }

  async getAllMetrics() {
    return this.prisma.activityMetric.findMany({
      orderBy: { recordedAt: 'asc' },
    });
  }
}
